version: '3'
services:
  postgres:
    image: 'postgres:13'
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: 'redis:4'
    ports:
      - "6379:6379"
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build: ./nginx
    ports:
      - '3050:80'
  api:
    build: ./server
    volumes:
      - ./server:/app
    env_file:
      - ./server/.env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8080 --reload
  client:
    environment:
      - WDS_SOCKET_PORT=0
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
  worker:
    build: ./worker
    volumes:
      - ./worker:/app
    env_file:
      - ./worker/.env

volumes:
  postgres_data: