services:
  client:
    image: 'ticokene20/multi-client:latest'
    mem_limit: 128m
    hostname: client
  server:
    image: 'ticokene20/multi-server:latest'
    mem_limit: 128m
    hostname: api
    env_file: ./server/.env
  worker:
    image: 'ticokene20/multi-worker:latest'
    mem_limit: 128m
    hostname: worker
    env_file: ./worker/.env
  nginx:
    image: 'ticokene20/multi-nginx:latest'
    mem_limit: 128m
    hostname: nginx
    ports:
      - '80:80'
