apiVersion: apps/v1
kind: Deployment
metadata:
  name: migration-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: migration
  template:
    metadata:
      labels:
        component: migration
    spec:
      initContainers:
        - name: wait-for-postgres
          image: postgres
          env:
            - name: POSTGRES_HOST
              value: postgres-cluster-ip-service
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: env
                  key: PG_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: env
                  key: PG_PASSWORD
          command: [ "sh", "-c", "until pg_isready -h $POSTGRES_HOST -U $POSTGRES_USER; do echo waiting for database; sleep 2; done;" ]

      containers:
        - name: migration-db
          image: ticokene20/multi-server
          env:
          - name: REDIS_HOST
            value: redis-cluster-ip-service
          - name: REDIS_PORT
            value: '6379'
          - name: PG_HOST
            value: postgres-cluster-ip-service
          - name: PG_PORT
            value: '5432'
          - name: PG_USER
            valueFrom:
              secretKeyRef:
                name: env
                key: PG_USER
          - name: PG_PASSWORD
            valueFrom:
              secretKeyRef:
                name: env
                key: PG_PASSWORD
          - name: PG_DATABASE
            valueFrom:
              secretKeyRef:
                name: env
                key: PG_DATABASE
          command: ["alembic", "upgrade", "head"]